
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPlusMinusleftMultiplyDivideAsmOperation Divide EndProg Equal False FunReturn Function GreaterThan GreaterThanOrEqual If Indent Jump LPAREN LowerThan LowerThanOrEqual Minus Multiply NotEqual Number Plus RPAREN RefJump StrictEqual True Variablejump : Jump Variable condition Indentcondition : True'
    
_lr_action_items = {'Jump':([0,],[2,]),'$end':([1,6,],[0,-1,]),'Variable':([2,],[3,]),'True':([3,],[5,]),'Indent':([4,5,],[6,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'jump':([0,],[1,]),'condition':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> jump","S'",1,None,None,None),
  ('jump -> Jump Variable condition Indent','jump',4,'p_jump','mainYacc.py',51),
  ('condition -> True','condition',1,'p_condition','mainYacc.py',55),
]
